"""
Name: LOGAN VAUGHAN
ID #:  1577489
CMPUT  274  EA1

Exercise  2: UnFair Dice
"""

import random

def biased_rolls(prob_list, s, n):
	"""
	Simulate n rolls of a biased m-sided die and return
    a list containing the results. 

    Arguments:
        prob_list: a list of the probabilities of rolling the 
                   number on each side of the m-sided die. The list  
                   will always have the length m (m >= 2), where m is 
                   the number of sides numbered 1 to m. Therefore,  
                   for example, the probability stored at index 0 in 
                   the list is the probability of rolling a 1 on
                   the m-sided die.
        s: the seed to use when initializing the PRNG
        n: the number of rolls to return

    Return:
        rolls: a list (of length n) containing each of the n rolls of the 
               biased die, in the order they were generated.
  	"""

  	#changes the random seed
	random.seed(s)

	rolls = [0] * n
	total = 0

	#Generates random decimal numbers in range of [0,1)
	for randNum in range(n):
		rolls[randNum] = random.random()
	#At this point the variable rolls is a list of randomly generated decimal numbers

	#Converts the random numbers from the variable rolls to a dice side based on the probabilities
	#If the random number is within 0 and the first probability then the roll is defermined to be side 1
	#If the random number is within the first probability and the sum of probabilities 1 and 2 then it will roll side 2 etc.
	for rollNum in range(n):
		for side in range(len(prob_list)):
			if rolls[rollNum] < prob_list[side] + total:
				rolls[rollNum] = side + 1
			else:
				total += prob_list[side]
		total = 0
	#Now the variable rolls is a list of the dice sides that have been rolled

	print(rolls)
	return rolls

def draw_histogram(m, rolls, width):
	"""
    Draws a frequency histogram of the rolls of an m-sided die
    mapped to a fixed width.

    Arguments: 
        m (int): the number of sides on the die
        rolls (list): the list of rolls generated by the biased die
        width (int): the fixed width of the histogram, in characters
                     (this is the length of the longest bar in the 
                     histogram, to maximize space in the chart)

    Returns:
        None (but prints the histogram to standard output)
    """

    #Creates the variable rollCounts
    #rollCounts is used it to store the numbers of times each dice side was rolled
	rollCounts = [0] * m
	for i in range(len(rolls)):
		for j in range(m):
			if rolls[i] == j + 1:
				rollCounts[j] += 1

	#Creates the variable starCounts
	#starCounts is used to store the number of stars that will be plotted on the histogram for each dice side 
	starCounts = [0] * m
	for i in range(m):
		starCounts[i] = round(rollCounts[i] * width / max(rollCounts))

	#Prints the histogram
	print("Frequency Histogram: {}-sided Die".format(m))
	for diceSide in range(m):
		print(diceSide + 1, end='')
		print(": ", end='')
		for i in range(starCounts[diceSide]):
			print("*", end='')
		for j in range(max(starCounts) - starCounts[diceSide]):
			print(".", end='')
		print()


if __name__ == "__main__":
	#Seed and number of rolls input
	randSeed = int(input("PRNG seed: "))
	numberOfRolls = int(input("Number of rolls: "))

	#Makes sure number of sides is at least 2
	numberOfSides = int(input("Number of sides: "))
	while numberOfSides < 2:
		print("There must be at least 2 sides.")
		numberOfSides = int(input("Number of sides: "))

	total = 0
	probabilities = [0] * numberOfSides

	#This section contains various checks to make sure the probabilities being entered are fractions and add to 1
	for side in range(numberOfSides):
		check = 1

		while check > 0:
			check = 0

			probabilities[side] = input("Input the probability of rolling on side {} in a fraction: ".format(side + 1))
			if probabilities[side] == "0":
				probabilities[side] = "0/1"

			while not("/" in probabilities[side]):
				print("Input must be a fraction.")
				probabilities[side] = input("Input the probability of rolling on side {} in a fraction: ".format(side + 1))
				if probabilities[side] == "0":
					probabilities[side] = "0/1"

			pieces = probabilities[side].split("/")

			if not(pieces[0].isdigit()) or not(pieces[1].isdigit()) or len(pieces) != 2 or pieces[1] == 0:
				print("Input must be in the form a/b where a and b are positive integers and b does not equal 0.")
				check += 1
			else:
				probabilities[side] = int(pieces[0]) / int(pieces[1])
				total += probabilities[side]

			if (round(total, 3) != 1 and side == numberOfSides - 1) or (total > 1 and side < numberOfSides - 1):
				print("All fractions must add up to 1.")
				total -= probabilities[side]
				check += 1

	#Histogram width input
	histWidth = int(input("Width of histogram: "))

	rolls = biased_rolls(prob_list = probabilities, s = randSeed, n = numberOfRolls)

	draw_histogram(m = numberOfSides, rolls = rolls, width = histWidth)